# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Evolution-X-Devices/kernel_oneplus_msm8998
          kernel-dir: kernel/oneplus/msm8998
          kernel-branch: vic
          config: lineage_oneplus5_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 15
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
          release : true
          access-token : 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

          
